### ISSUE TITLE
Endomondo gpx export bug

### ISSUE THREAD

**Issue by skjeggape** [ChristopheSeg/J-TrackGallery#23]
Hello.

I'v discovered that gpx exports from endomondo have I curious behaviour.  It draws a line from start to stop automatically and adds that distance to the total, if it's 1km the route shows as 1km longer than it should be.

I'll try and add a gpx export file and screenshot from j!tracks gallery.

**Comment by skjeggape** [comment]
Here's a picture.
![dsc_0029](https://cloud.githubusercontent.com/assets/13901439/9405645/d1761afc-47f9-11e5-8358-10322324c8e9.JPG)

**Comment by skjeggape** [comment]
Here's link to the gpx file I have exported from endomondo. 
https://drive.google.com/file/d/0B-fGxf9Y3_PneHNoLVpTZnZvOFE/view?usp=docslist_api

**Comment by ChristopheSeg** [comment]
Thank for reporting this bug. Strange annoying behaviour! I will loolk at this.

**Comment by ChristopheSeg** [comment]
This is fixed in next 0.9.15 (Multiple Tracks GPX files where read improperly, and eldomondo gpx files contain a second track with only one point!)
