### ISSUE TITLE
Bug report - waypoint icons and tracks display refresh

### ISSUE THREAD

**Issue by koutipik** [ChristopheSeg/J-TrackGallery#27]
Hello Christophe,

Very nice add-on, thank you for your work !

. Little bug 
It seems impossible to unactive the waypoint icon in the tracks list, whatever is set in the parameters. It works with other icons.

. Annoying bug
The display of tracks/maps seems bugged when Joomla cache is activated : after cleaning all caches (Joomla, navigator), the fisrt tracks to be displayed is ok, but after you get nearly anywhat : blank map, previous tracks...
My site is small, so I solved the issue by desactivating Joomla cache, but it would not be possible for everybody.

Best regards,

Anne

**Comment by ChristopheSeg** [comment]
Many thanks Anne
Every little bug must be corrected. I didn't saw these ones. 

Unactivating Waypoint icon will work in next 0.9.22 version (very soon)

For Caching, it is in fact important the component works with cache. I will investigate to fix this.
