### ISSUE TITLE
import files : require regex to clean tittle/name included in gpx file

### ISSUE THREAD

**Issue by bcag2** [ChristopheSeg/J-TrackGallery#28]
In GPX file, if the field <name> contain bad letter than ', the import return an error 1064.
In my case : title='2013 VTT N° B5 Le bois D'Avrillat'.
I suggest use regex : 
<code>function clean($in) {
    $in=htmlentities("$in");
    return preg_replace('/&(.)(.*?);/', '$1', $in);     
} </code>

**Comment by ChristopheSeg** [comment]
Thank you for reporting this error. 
The title is now escaped and quoted. I further will inspect other title end description  (maps; category; terrain tables) who also may need quoting and escaping.
