### ISSUE TITLE
field 'usepace' no more existing in jtg_cats categories table

### ISSUE THREAD

**Issue by bcag2** [ChristopheSeg/J-TrackGallery#29]
So I would like add a new categorie and it return an error 
<code>
1054 Unknown column 'usepace' in 'field list' SQL=INSERT INTO xxxx_jtg_cats SET parent_id='0', title='Ski de randonnée', image='symbol_inter.png', usepace='0', default_map='11', default_overlays='a:1:{i:0;i:0;}', description='',
published='1'
</code>
Thanks to correct the request

**Comment by ChristopheSeg** [comment]
This bug appears in 0.9.22 fresh install, it is corrected in future version. if the bug appears in 0.9.22 (fresh install) please manually upgrade with to last version.
