### ISSUE TITLE
Latest version does not display maps

### ISSUE THREAD

**Issue by mastervanleeuwen** [ChristopheSeg/J-TrackGallery#31]
Hi,
 
I just installed the latest version 0.9.25 of J-trackgallery and it does not show maps:

http://gta-trek.eu/index.php/gps-tracks/files/file/18

I had been playing with 0.9.22 on a local installation at home and there the maps work. Do you have any suggestions for what to try?

The icons for buttons etc also do not seem to be uploaded. I got an error that the path ~/public_html/images/jtrackgallery or so was not found during installation...

Any help is appreciated,

Marco.

**Comment by mastervanleeuwen** [comment]
Never mind, I solved this by creating and adding an API key, as explained here:

https://wordpress.org/support/topic/google-maps-api-error-missingkeymaperror-1/

Note that you need to change the script URL for each Google map version (Street, Satellite, Hybrid, etc), because otherwise it will include the API twice:

	<script src="http://maps.google.com/maps/api/js?v=3&sensor=false"></script>
	<script src="http://maps.google.com/maps/api/js?v=3&sensor=false&key=<mykey>"></script>

**Comment by ChristopheSeg** [comment]
Glad you solved it. The issue is also explained here http://jtrackgallery.net/kunena/j-track-gallery-issues/97-google-maps-api-key-issue#215
Note that the sensor parameter is no longer used so we can use one of these line for Google maps script:
```
http://maps.google.com/maps/api/js?v=3
http://maps.google.com/maps/api/js?v=3&key=<mykey>
```
