### ISSUE TITLE
template.css not found

### ISSUE THREAD

**Issue by mastervanleeuwen** [ChristopheSeg/J-TrackGallery#32]
Dear Christophe,

When using the Joomgallery plugin (and looking at the pages in developer mode), I got a warning that:

<my_base_url>/components/com_jtg/template.css does not exist

This files seems to be located in 
<my_base_url>/administrator/components/com_jtg/template.css 

So I think the fix is to change line 172 of the jtrackgallery_maps.php file to:
		$document->addStyleSheet(JUri::base(true) . '/administrator/components/com_jtg/template.css');

There are similar links in the following files:
administrator/components/com_jtg/views/files/tmpl/form.php
administrator/components/com_jtg/views/files/tmpl/default.php
administrator/components/com_jtg/views/files/tmpl/element.php

I have not fully checked whether those are OK.

Best regards,

Marco.

**Comment by ChristopheSeg** [comment]
I will have a look. You are probably right.
