### ISSUE TITLE
Vue générale pas de carte 

### ISSUE THREAD

**Issue by chrislegallic** [ChristopheSeg/J-TrackGallery#33]
Bonjour, 

j'essaye d'utiliser le module JTrack Gallery. 
Dans mon menu utilisateur, j'ai sélectionné "Liste des traces (tableau) 
A l'affichage, la liste apparait bien mais je n'ai pas de carte avec les traces 
Pouvez vous m'aider? 
Je n'ai pas trouver dans le wiki, et le site test ne semble plus être à jour. 

Merci de votre aide
Chris
www.vttmarsien.fr

**Comment by ChristopheSeg** [comment]
Bonjour 
La liste des traces apparait sous forme d'une liste
http://demoj25.jtrackgallery.net/index.php/en/component/jtg/files/list
ou sous forme d'un aperçu général sur une carte 
http://demoj25.jtrackgallery.net/index.php/en/component/jtg/
L'aperçu fait parti des liens de menu disponible lorsque l'on ajout un item dans un menu

As-tu un site de démo en ligne? (tu peux me contacter directement christophe@jtrackgallery.net)
