### ISSUE TITLE
Waypoints PoI and Images Gallery

### ISSUE THREAD

**Issue by joomleb** [ChristopheSeg/J-TrackGallery#43]
Hi guys,
Please, Is there a way to add some images Waypoints (like points of interest) and show them in the Image Gallery ?

Can you address us on the right way to do it ?

**Comment by mastervanleeuwen** [comment]
Hi,

If you upload an image file that has GPS coordinates stored in the file (exif information) it will automatically show the location with a marker on the map. 
See for example here: https://testing.gta-trek.eu/index.php/j-trackgallery/files/file/19
click on the camera icons to see the pictures. 

Is that what you have in mind?

Best regards, Marco.

**Comment by joomleb** [comment]
@mastervanleeuwen Yes, you are right, many thanks!

**A** - As far as I see from the demo page, clicking on the "x" does not close the tooltip. Fom my point of view you can just take over the "x" icon, because clicking out the tooltip close it... - I add an image for you

**B** - Can the Gallery Images work with both images and videos in a mixed way ? (Can we also upload small videos?)

**C** - To don't overload our Server we are moving all the "Uploads" (images and videos) to embed Google Photo shared Photos URLs, [here an example](https://www.youtube.com/watch?time_continue=126&v=InKJcbOgf9k&feature=emb_title) just copying and pasting the URLs, and/or Google Photo shared Album (so, when a Photo/Video is added to the Album from our collaborators, it is automatically shown on the site). Please, Can you consider it for next release ?

PS - For the future, Please, Do I have always to post here: https://github.com/mastervanleeuwen/J-TrackGallery/issues  ?

**Comment by joomleb** [comment]
I close this and I will re open it, ordered and updated, into https://github.com/mastervanleeuwen/J-TrackGallery/issues ...
