### ISSUE TITLE
Joomla 4 und Php 8 Probleme

### ISSUE THREAD

**Issue by GStautner** [ChristopheSeg/J-TrackGallery#44]
Möchte gerne J!Track Gallery unter Joolma 4 weiterbenutzen und php 8 verwenden. Unter php 7.4 lief es sehr gut mit der Version 0.9.33

Jetzt unter php 8 gibt es Probleme 
Non-static method JtgMapHelper::parseTracksInfoJS() cannot be called statically
/homepages/38/d820037332/htdocs/ZZZ_NeueSeiten/Joomla4/components/com_jtg/helpers/maphelper.php (135)

gibt es da eine Lösung

Danke

**Comment by mastervanleeuwen** [comment]
Thanks for your message. 

Could you try this version: https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33a.zip
This is a test version that contains a minor bugfix which I think will solve this problem. Please let me know whether it works; I will then update the official release with this fix.

Also note that this issue tracker is connected to repository of an older version of J!TrackGallery. The development version has been moved to my repository, with this issue page: https://github.com/mastervanleeuwen/J-TrackGallery/issues  . If you encounter more/other issues, please post them there.

Best regards, Marco.

**Comment by GStautner** [comment]
Danke für die schnelle Antwort.
Der Fix ist Ok  - jetzt läuft es auch unter php 8

Ich habe in der alten Version noch den Gehzeitrechner mit Höhenberücksichtigung (variable Steig- und Abstiegswerte Hm/h) eingefügt. Die Software ist Spitze!!

![grafik](https://user-images.githubusercontent.com/93383695/145029803-ca563673-03af-4d95-a19e-8d0fd4c32125.png)
![grafik](https://user-images.githubusercontent.com/93383695/145029852-1c570e2b-c2d6-474e-be41-06a590fda51b.png)

**Comment by GStautner** [comment]
Habe noch ein Problem festgestellt - das Höhenprofil wird nicht angezeigt - nur graue Fläche
![grafik](https://user-images.githubusercontent.com/93383695/145031390-09e15bd2-52e9-41c6-a478-e9096842a1e4.png)
